import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { SidebarProvider } from "@/components/ui/sidebar";
import { Header } from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

// Accept a Sidebar component dynamically
export default function DepartmentLayout({
  children,
  SidebarComponent
}: Readonly<{
  children: React.ReactNode;
  SidebarComponent: React.ElementType;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <SidebarProvider>
            <div className="flex flex-row h-full w-[100vw]">
              {/* Dynamically render the passed Sidebar */}
              <SidebarComponent />
              <div className="flex flex-col flex-1">
                <Header />
                <div className="children p-4 overflow-auto">
                  {children}
                  <Toaster />
                </div>
              </div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
