import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { NavigationMenu } from "../components/navigationmenu";
import { Header } from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function Layout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  ${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen`}>
        <SidebarProvider>
          <div className="flex flex-row h-full w-full">
            <NavigationMenu />
            <div className="flex flex-col flex-1 ">
              <Header />
              <div className="children  p-4 overflow-auto">
                {children}
                <Toaster />
              </div>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
